### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by FlorianWendelborn** [amandeepmittal/robotize#1]
I'd like to be able to actually use this in projects, unfortunately there is no LICENSE file. A fix would be appreciated, thanks!

**Comment by ghost** [comment]
No problem, thanks for the reminder

**Comment by ghost** [comment]
The license is MIT btw

**Comment by FlorianWendelborn** [comment]
@ismay Yes, I know, I saw that. Problem is that we need something that we can copy-paste to our licenses file for the used dependencies. We can't just "invent" the MIT header ourselves. 🙁

**Comment by ghost** [comment]
Sorry, I thought you meant the license was missing. But just realised it's in the readme. If you need a specific license feel free to use https://ismay.mit-license.org/. If you really need it to be in a file in the repo a PR is always welcome.
