### ISSUE TITLE
Interested in adopting this package.

### ISSUE THREAD

**Issue by amandeepmittal** [amandeepmittal/robotize#2]
Hi,
I am interested in adopting this package.

**Comment by ghost** [comment]
Cool! Shall I transfer it to your personal github account? And which npm account do you want me to transfer the npm rights to?

**Comment by amandeepmittal** [comment]
This is my github profile link: https://github.com/amandeepmittal
and npm link: https://www.npmjs.com/~amandeepmittal

**Comment by ghost** [comment]
![screen shot 2017-11-21 at 16 38 17](https://user-images.githubusercontent.com/7355199/33081349-6d712f6e-ceda-11e7-94de-59bcdad46b85.png)

Being transferred now. Apparently you can't transfer directly from an org 🤦‍♂️ . You have the npm rights already.

**Comment by ghost** [comment]
You should have received an email asking if you want to accept the transfer from github.

**Comment by amandeepmittal** [comment]
I haven't received the email yet. Does it suppose to take time?

**Comment by ghost** [comment]
Don’t think so. Did you check your spam? It uses your primary github email I assume

**Comment by ghost** [comment]
Rerequested the transfer.

**Comment by amandeepmittal** [comment]
I did check my spam and currently logged in to my primary github email. Still haven't got it.

**Comment by ghost** [comment]
Hmm that's weird. Would you mind emailing github support about it and posting back here? In the meantime I'll see what I can figure out. Annoying..

**Comment by amandeepmittal** [comment]
Sure, I'll do that.

**Comment by ghost** [comment]
From their [docs](https://help.github.com/articles/about-repository-transfers/):

> When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete.

So seems like you should receive an email about it on the email in your settings.

**Comment by amandeepmittal** [comment]
I have done transfers before. Transferred my repos to few orgs, did receive the email of confirmation. That's what seem weird to me this time.

**Comment by ghost** [comment]
> I have done transfers before. Transferred my repos to few orgs, did receive the email of confirmation. That's what seem weird to me this time.

Yeah strange. I have no idea why it isn't working. I've transfered repo's before as well, without problems. I'll message support as well and'll keep you posted.

**Comment by ghost** [comment]
So just received a reply from Shawna from github. Apparently it’s something she emailed you about as well and that should be resolved on your end?

**Comment by amandeepmittal** [comment]
Due to Timezone difference, sorry about yesterday. Yeah received the email. She told me to add an alternate email address. Let me do that and I will get back to you.

**Comment by amandeepmittal** [comment]
@ismay sorry about the inconvenience. Can you please transfer the repo again? I have changed my email as per Shawna's instructions from github.

**Comment by ghost** [comment]
> sorry about the inconvenience. Can you please transfer the repo again? I have changed my email as per Shawna's instructions from github.

No problem 👍  I aborted and restarted the transfer. Let me know if I need to do anything else!

**Comment by amandeepmittal** [comment]
Haha it's getting weird from my side. Looks like there is some problem with my Github account. I haven't received the notification in email yet. Can you please try transferring one more time?

**Comment by ghost** [comment]
@amandeepmittal Done

**Comment by amandeepmittal** [comment]
Thanks @ismay Got it! Sorry for the trouble. You are very patient.
I think we can close this issue since the mission is accomplished 😄

**Comment by ghost** [comment]
:) No problem, glad it worked and thanks for adopting it!
